django_skillbox/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns

from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagget/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),

    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
         )
]

# urlpatterns += i18n_patterns(
#     path('myauth/', include('myauth.urls')),
#     path('shop/', include('shopapp.urls')),
# )

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    logout_view,
    AboutMeView,
    RegisterView,
    FooBarView,
    # UpdateAvatarView,
    # HelloView,
)


app_name = 'myauth'

urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='myauth/login.html',
             redirect_authenticated_user=True,
         )
         , name='login'),
    path('logout/', logout_view, name='logout'),
    path('about-me', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    # path('update/<int:pk>/', UpdateAvatarView.as_view(), name='update-avatar'),
    # path('hello/', HelloView.as_view(), name='hello'),

    path('cookie/set', set_cookie_view, name='cookie-set'),
    path('cookie/get', get_cookie_view, name='cookie-get'),

    path('session/set', set_session_view, name='session-set'),
    path('session/get', get_session_view, name='session-get'),
    path('foo-bar/', FooBarView.as_view(), name='foo-bar')
]

shopapp/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from django.views.decorators.cache import cache_page

from .views import (ShopIndexView,
                    GroupsListView,
                    ProductDetailView,
                    ProductListView,
                    OrdersListView,
                    OrderDetailView,
                    UpdateProductView,
                    ProductDeleteView,
                    OrderUpdateView,
                    CreateProductView,
                    OrderCreateView,
                    OrderDeleteView,
                    OrderExportView,
                    ProductViewSet,
                    OrderViewSet,
                    ProductsDataExportView,
                    LatestProductsFeed,
                    UsersOrderList,
                    UserOrderExportView,
                    )


orders_router = DefaultRouter()
orders_router.register('orders', OrderViewSet)

product_router = DefaultRouter()
product_router.register('products', ProductViewSet)

app_name = 'shopapp'

urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),
    path('api/', include(product_router.urls)),
    path('api/', include(orders_router.urls)),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('products/', ProductListView.as_view(), name='products_list'),
    path('products/latest/feed/', LatestProductsFeed(), name='products_feed'),
    path('products/export/', ProductsDataExportView.as_view(), name='products-export'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
    path('products/<int:pk>/update/', UpdateProductView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('products/create/', CreateProductView.as_view(), name='create_product'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_details'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('orders/create/', OrderCreateView.as_view(), name='create_order'),
    path('orders/export/', OrderExportView.as_view(), name='order_export'),
    path('users/<int:user_id>/orders/', UsersOrderList.as_view(), name='users_orders_list'),
    path('orders/<int:user_id>/export/', UserOrderExportView.as_view(), name='users_orders_export'),
]

shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


def poduct_preview_directory_path(instance: 'Product', filename: str) -> str:
    return 'products/product_{pk}/preview/{filename}'.format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно купить в интернет магазине.

    Заказы тут:model:`shopapp.Order`
    """
    class Meta:
        ordering = ['name', 'price']
        # verbose_name_plural = 'products'

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to='')
    # created_by = models.ForeignKey(User, on_delete=models.CASCADE, default=1, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('shopapp:product-detail', kwargs={'pk': self.pk})

    def __str__(self) -> str:
        return f'Product (pk={self.pk}, name={self.name!r})'


def product_image_directory_path(instance: 'ProductImage', filename: str) -> str:
    return 'products/product_{pk}/image/{filename}'.format(
        pk=instance.product.pk, filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_image_directory_path)
    description = models.TextField(max_length=200, null=False, blank=True)


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')
    receipt = models.FileField(null=True, upload_to='orders/receipt/')

shopapp/views.py
import logging
from rest_framework.decorators import action
from csv import DictWriter

from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.contrib.auth.models import Group, User
from django.core.exceptions import PermissionDenied
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render, redirect, reverse, get_object_or_404, resolve_url
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator

from timeit import default_timer

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django_filters.rest_framework import DjangoFilterBackend

from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DeleteView,
    DetailView,
    CreateView,
    UpdateView
)

from .models import Product, Order, ProductImage

from .common import save_csv_products
from rest_framework.viewsets import ModelViewSet
from rest_framework.parsers import MultiPartParser
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.request import Request
from rest_framework.response import Response
from .serializers import ProductSerializer, OrderSerializer
from rest_framework.views import APIView

from .forms import ProductForm, OrderForm, GroupForm

from django.contrib.syndication.views import Feed

from django.views import View

from drf_spectacular.utils import extend_schema


log = logging.getLogger(__name__)


@extend_schema('description = Product views CRUD')
class ProductViewSet(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [SearchFilter, DjangoFilterBackend, OrderingFilter]
    search_fields = ['name', 'description']
    filterset_fields = [
        'name',
        'description',
        'price',
        'discount',
        'archived',
    ]
    ordering_fields = [
        'name',
        'price',
        'discount',
    ]

    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        return super().list(*args, **kwargs)

    @action(methods=['get'], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type='text/csv')
        filename = 'products-export.csv'
        response['Content-Disposition'] = f'attachment; filename={filename}'
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            'name',
            'description',
            'price',
            'discount',
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })

        return response

    @action(
        detail=False,
        methods=['post'],
        parser_classes=[MultiPartParser]
    )
    def upload_csv(self, request: Request):
        products = save_csv_products(
                request.FILES['file'],
                encoding=request.encoding,
             )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [SearchFilter, DjangoFilterBackend, OrderingFilter]
    search_fields = ['user', 'delivery_address']
    filterset_fields = [
        'delivery_address',
        'user',
        'products',
        'promocode',
    ]
    ordering_fields = [
        'pk',
        'delivery_address',
        'user',
        'products',
    ]


class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]

        context = {
            'time_running': default_timer(),
            'products': products,
            'items': 5,
        }
        log.debug('Products for shop index: %s', products)
        log.info('Rendering shop index')
        print('shop imdex context', context)
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            'form': GroupForm(),
            'groups': Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest) -> HttpResponse:
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)


class ProductDetailView(DetailView):
    template_name = 'shopapp/products-dateils.html'
    queryset = Product.objects.prefetch_related('images')
    context_object_name = 'product'

    def get(self, request: HttpRequest, pk: int) -> HttpResponse:
        product = get_object_or_404(Product, pk=pk)
        context = {
            'product': product
        }
        return render(request, 'shopapp/products-dateils.html', context=context)


class ProductListView(ListView):
    template_name = 'shopapp/products-list.html'
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)


class CreateProductView(CreateView):
    # permission_required = 'shopapp.add_product'
    queryset = Product.objects.select_related('user')
    fields = 'name', 'price', 'description', 'discount', 'preview'
    template_name = 'shopapp/product_form.html'
    success_url = reverse_lazy('shopapp:products_list')

    # def form_valid(self, form):
    #     form.instance.created_by = self.request.user
    #     return super().form_valid(form)


class UpdateProductView(PermissionRequiredMixin, UpdateView):
    permission_required = 'shopapp.change_product'
    # template_name = 'shopapp/product_form.html'
    fields = 'name', 'price', 'description', 'discount', 'preview'
    template_name_suffix = '_update_form'
    model = Product
    # form_class = ProductForm

    def get_success_url(self):
        return reverse(
            'shopapp:product_details',
            kwargs={'pk': self.object.pk}
        )

    # def form_valid(self, form):
    #     response = super().form_valid(form)
    #     for image in form.files.getlist('images'):
    #         ProductImage.objects.create(
    #             product=self.object,
    #             image=image,
    #         )
    #     return response
    #
    # def get_queryset(self):
    #     return Product.objects.filter(created_by=self.request.user).select_related('created_by')


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class LatestProductsFeed(Feed):
    title = 'Products (latest)'
    description = 'Products description'
    link = reverse_lazy('shopapp:products_list')

    def items(self):
        return (
            Product.objects.only(
                'name', 'description',
                'price', 'preview'
            )[:5]
        )

    def item_title(self, item: Product):
        return item.name

    def item_link(self, item: Product):
        return item.description


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
        .select_related('user')
        .prefetch_related('products')
    )
    context_object_name = 'orders'


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'shopapp.view_order'
    queryset = (
        Order.objects
        .select_related('user')
        .prefetch_related('products')
    )


def create_order(request: HttpRequest):
    if request.method == 'GET':
        form = OrderForm(request.GET)
        if form.is_valid():
            form.save()
            url = reverse('shopapp:orders_list')
            return redirect(url)
    else:
        form = OrderForm()

    context = {
        'form': form
    }
    return render(request, 'shopapp/create-order.html', context=context)


class OrderCreateView(CreateView):
    queryset = Order.objects.select_related('user').prefetch_related('products')
    success_url = 'shopapp:orders_list'
    fields = 'user', 'products', 'delivery_address', 'promocode'
    template_name = 'shopapp/order_form.html'


class OrderUpdateView(UpdateView):
    queryset = Order.objects.select_related('user').prefetch_related('products')
    fields = 'user', 'products', 'delivery_address', 'promocode'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopapp:order_details',
            kwargs={'pk': self.object.pk}
        )


class UsersOrderList(LoginRequiredMixin, ListView):
    queryset = Order
    context_object_name = 'orders'
    template_name = 'shopapp/users-orders-list.html'

    def get_queryset(self):
        user_id = self.kwargs['user_id']
        try:
            user = User.objects.get(pk=user_id)
        except User.DoesNotExist:
            raise Http404('User not found')
        return Order.objects.filter(user_id=user_id)


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('shopapp:orders_list')


class OrderExportView(UserPassesTestMixin, View):
    queryset = Order.objects.select_related('user').prefetch_related('products').all()
    template_name = 'shopapp:order-export.html'

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest) -> JsonResponse:

shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
    Base body
{% endblock %}

<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    Today is 
    {{ current_weekday }}
</div>
</body>
</html>

shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create Product
{% endblock %}

{% block body %}
    <h1>Create Product</h1>

    <div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <button type="submit">Create product</button>
        
    </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Back to Products List
        </a>
    </div>

{% endblock %}

shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups list
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    </div>
    <div>
    {% if not groups %}
        <h3>No groups</h3>
    {% else %}
        <ul>

            {% for group in groups %}
                <li>
                    <div>{{ group.name }}</div>
                    <ul>
                        {% for permission in group.permissions.all %}
                            <li>
                                {{ permission.name }}
                                (<code>{{ permission.codename }}</code>)
                            </li>
                        {% endfor %}    
                    </ul>
                </li>
            {% endfor %}

        </ul>
    {% endif %}
    </div>
{% endblock %}

shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create Order
{% endblock %}

{% block body %}
    <h1>Create Order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url "shopapp:orders_list" %}">Back to orders list</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders List
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if orders %}
        <div>
            {% for order in orders %}
                <div>
                    <p><a href="{% url "shopapp:order_details" pk=order.pk %}">Details #{{ order.pk }}</a></p>
                    <p>Order by {% firstof orders.user.first_name order.user.username %}</p>
                    <p>Promocode {{ order.promocode }}</p>
                    <p>Delivery address {{ order.delivery_address }}</p>
                    <div>
                        Products in order:
                        <ul>
                            {% for product in order.products.all %}
                                <li>
                                ({{ product.name }} for ${{ product.price }})
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        
        </div>
            <a href="{% url 'shopapp:create_order' %}">
            Create a new order
            </a>
        <div>
        
        </div>
        
    {% else %}
        <h3>No orders</h3>
    {% endif %}
{% endblock %}

shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update Order
{% endblock %}

{% block body %}
    <h1>Update Order #{{ object.pk }}</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url "shopapp:order_details" pk=object.pk %}">Back to Order #{{ object.pk }}</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
    {% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_orders_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm Archived
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk%}">Back to product</a>
    </div>
    <br>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Archived</button>
    </form>
    </div>
{% endblock %}

shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create Product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    </div>
    <div>
    <a href="{% url "shopapp:products_list" %}">Back to products list</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update Product
{% endblock %}

{% block body %}
    <h1>Update product</h1>
    <div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
    </div>
    <div>
    <a href="{% url "shopapp:product_details" pk=object.pk %}">Back to products #{{ object.pk }}</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/products-dateils.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block body %}
{#    {% blocktranslate %}#}
        <h1>Product <strong>{{ product.name }}</strong></h1>
        <div>
            <div>Description: <em>{{ product.description }}</em></div>
            <div>Price: {{ product.price }}</div>
            <div>Discount: {{ product.discount }}</div>
            <div>Archived: {{ product.archived }}</div>
{#    {% endblocktranslate %}    #}
    
         {% if product.preview %}
             <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
         {% endif %}

        <h3>{% translate 'Images' %}</h3>
        <div>
            {% for image in product.images.all %}
                <img src="{{ image.image.url }}" alt="{{ image.image.name }}">
                <div>{{ image.description }}</div>
            {% empty %}    
                <div>{% translate 'No images yet' %}</div>
            {% endfor %}
        </div>
        
        <a href="{% url "shopapp:product_update" pk=product.pk %}">{% translate 'Update Product' %}</a>
    </div>
    <div>
        <a href="{% url "shopapp:product_delete" pk=product.pk %}">{% translate 'Archived Product' %}</a>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">{% translate 'Back to products list' %}</a>
    </div>
{% endblock %}

shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Product list' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Products' %}:</h1>
    {% if products %}
        <div>
            {% blocktranslate count product_count=products|length %}
                There is only one product.
                {% plural %}
                There are {{ product_count }} products.
            {% endblocktranslate %}
        </div>
        <div>
            {% for product in products %}
                <div>
                    <p><a href="{% url "shopapp:product_details" pk=product.pk %}">{% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
                    <p>{% translate 'Price' %}: {{ product.price }}</p>
                    {% translate 'No discount' as no_disct %}
                    <p>{% translate 'Discount' %}: {% firstof product.discount no_disct %}</p>

                    {% if product.preview %}
                        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">

                    {% endif %}
                </div>
            {% endfor %}

             <div>
        {% if perms.shopapp.add_product %}
             <a href="{% url "shopapp:create_product" %}">{% translate 'Create a new product' %}</a>
        {% endif %}
        </div>


    {% else %}
        {% url "shopapp:create_product" as create_product_url%}
        {% blocktranslate %}
            <h3>No products yet</h3>
            <a href="{{ create_product_url }}"
            >Create a new product</a>
        {% endblocktranslate %}
    {% endif %}

{% endblock %}

shopapp/templates/shopapp/user_order_export.html
{% extends 'shopapp/base.html' %}

{% block title %}
    User Order Export
{% endblock %}

{% block body %}
    <h1>Export Order</h1>
    <form method="get">
        {% csrf_token %}
        {{ form.as_p }}
    </form>
{% endblock %}

shopapp/templates/shopapp/users-orders-list.html
{% extends 'shopapp/base.html' %}

{% load cache %}

{% block title %}
    User orders
{% endblock %}

{% block body %}
    <h1>Orders by {{ orders.first.user.username }}:</h1>
    {%  cache 300 order_info   %}
        {% for order in orders %}
            <p>Delivery address: {{ order.delivery_address }}</p>
            <p>Promocode: {{ order.promcode }}</p>
            <p>Products in order:</p>
            {% for product in order.products.all %}
                <li>
                    ({{ product.name }} for {{ product.price }}$)
                </li>
            {% endfor %}    
        {% endfor %}
    {% endcache %}
{% endblock %}